[package]
name = "ecsrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "ecsrs"
path = "src/lib.rs"
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste="1.0.7"
